#!/bin/bash
# === SMK STARTSIDA FELSÖKNING ===
# Kör från valfri dator med SSH/WP-CLI access till SMK:s Loopia
# Alternativ: kör stegen manuellt via Loopia filhanterare
#
# Problem: Startsidan på smalandskontorsmobler.se visar kod/är trasig
# Trolig orsak: Code Snippets-plugin eller tema-konflikt

echo "============================================"
echo "  SMK Startsida — Felsökningsguide"
echo "============================================"
echo ""
echo "=== STEG 1: Kolla felloggar ==="
echo "Loopia → Webbhotell → Filhanterare"
echo "Öppna: wp-content/debug.log"
echo "Öppna: error_log (i roten)"
echo "Kopiera de senaste 50 raderna → ge till Claude"
echo ""
echo "=== STEG 2: Aktivera WP debug (via Loopia filhanterare) ==="
echo "Redigera wp-config.php, hitta WP_DEBUG och ändra till:"
echo ""
echo "  define('WP_DEBUG', true);"
echo "  define('WP_DEBUG_LOG', true);"
echo "  define('WP_DEBUG_DISPLAY', false);"
echo ""
echo "Ladda om startsidan, kolla sedan wp-content/debug.log"
echo ""
echo "=== STEG 3: Inaktivera Code Snippets (snabbfix) ==="
echo "Loopia → Filhanterare → wp-content/plugins/"
echo "Byt namn: code-snippets/ → code-snippets-OFF/"
echo "Ladda om startsidan — fungerar den nu?"
echo "  JA → En snippet är trasig. Byt tillbaka, gå in i WP-admin,"
echo "       Snippets → inaktivera en åt gången"
echo "  NEJ → Gå till steg 4"
echo ""
echo "=== STEG 4: Inaktivera ALLA plugins ==="
echo "Byt namn: wp-content/plugins/ → wp-content/plugins-OFF/"
echo "Ladda om startsidan — fungerar den?"
echo "  JA → Det är en plugin. Skapa ny plugins/ mapp,"
echo "       flytta tillbaka en plugin åt gången tills felet uppstår"
echo "  NEJ → Gå till steg 5"
echo ""
echo "=== STEG 5: Byt till standardtema ==="
echo "Byt namn: wp-content/themes/flavor/ → wp-content/themes/flavor-OFF/"
echo "  (eller flatsome/ eller generatepress/ — det aktiva temat)"
echo "WP faller tillbaka på Twenty Twenty-Five"
echo "Ladda om — fungerar den?"
echo "  JA → Temat är trasigt"
echo "  NEJ → Problem i WordPress core eller wp-config.php"
echo ""
echo "=== STEG 6: Nukleär — byt alla plugins tillbaka ==="
echo "GLÖM INTE att byta tillbaka alla mappar:"
echo "  plugins-OFF/ → plugins/"
echo "  code-snippets-OFF/ → code-snippets/"
echo "  flavor-OFF/ → flavor/"
echo ""
echo "============================================"
echo "  Ge Claude felloggen så fixar vi det"
echo "============================================"
